# Generated by Django 6.0.7 on 2026-08-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sames',
            field=models.IntegerField(default=0),
        ),
    ]
