# Generated by Django 6.0.7 on 2026-08-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_total_sales_amount_product_total_sames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_sames',
            new_name='total_sales',
        ),
    ]
